import "./globals.css";
import RecoilPreferences from "@/app/recoilPreferences";
import ReactLifeCycleSetting from "@/app/reactLifeCycleSetting";
import ContentLayout from "@/app/contentLayout";
import Header from "@/components/Header";
import Drawer from "@/components/Drawer";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="ko">
            <body>
                <RecoilPreferences>
                    <ReactLifeCycleSetting>
                    <Header />
                    <Drawer />
                    <ContentLayout>{children}</ContentLayout>
                    </ReactLifeCycleSetting>
                </RecoilPreferences>
            </body>
        </html>
    );
}
